// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/trpc/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/forum": {
    params: {};
  };
  "/app/forum/make": {
    params: {};
  };
  "/app/forum/:postId": {
    params: {
      "postId": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/*" | "/api/trpc/*" | "/app" | "/app/forum" | "/app/forum/make" | "/app/forum/:postId" | "/auth/login" | "/auth/signup";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api/auth.ts": {
    id: "routes/api/auth";
    page: "/api/auth/*";
  };
  "routes/api/trpc.ts": {
    id: "routes/api/trpc";
    page: "/api/trpc/*";
  };
  "routes/app/home.tsx": {
    id: "routes/app/home";
    page: "/app";
  };
  "routes/app/forum/list.tsx": {
    id: "routes/app/forum/list";
    page: "/app/forum";
  };
  "routes/app/forum/makePost.tsx": {
    id: "routes/app/forum/makePost";
    page: "/app/forum/make";
  };
  "routes/app/forum/viewpost.tsx": {
    id: "routes/app/forum/viewpost";
    page: "/app/forum/:postId";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/auth/signup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/api/auth": typeof import("./app/routes/api/auth.ts");
  "routes/api/trpc": typeof import("./app/routes/api/trpc.ts");
  "routes/app/home": typeof import("./app/routes/app/home.tsx");
  "routes/app/forum/list": typeof import("./app/routes/app/forum/list.tsx");
  "routes/app/forum/makePost": typeof import("./app/routes/app/forum/makePost.tsx");
  "routes/app/forum/viewpost": typeof import("./app/routes/app/forum/viewpost.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
};